defmodule Lago.AppliedCouponObjectExtended do
  @moduledoc """
  Provides struct and type for a AppliedCouponObjectExtended
  """

  @type t :: %__MODULE__{
          amount_cents: integer | nil,
          amount_cents_remaining: integer | nil,
          amount_currency: String.t() | nil,
          coupon_code: String.t() | nil,
          coupon_name: String.t() | nil,
          created_at: DateTime.t() | nil,
          credits: [Lago.CreditObject.t()] | nil,
          expiration_at: DateTime.t() | nil,
          external_customer_id: String.t() | nil,
          frequency: String.t() | nil,
          frequency_duration: integer | nil,
          frequency_duration_remaining: integer | nil,
          lago_coupon_id: String.t() | nil,
          lago_customer_id: String.t() | nil,
          lago_id: String.t() | nil,
          percentage_rate: String.t() | nil,
          status: String.t() | nil,
          terminated_at: DateTime.t() | nil
        }

  defstruct [
    :amount_cents,
    :amount_cents_remaining,
    :amount_currency,
    :coupon_code,
    :coupon_name,
    :created_at,
    :credits,
    :expiration_at,
    :external_customer_id,
    :frequency,
    :frequency_duration,
    :frequency_duration_remaining,
    :lago_coupon_id,
    :lago_customer_id,
    :lago_id,
    :percentage_rate,
    :status,
    :terminated_at
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amount_cents: {:union, [:integer, :null]},
      amount_cents_remaining: {:union, [:integer, :null]},
      amount_currency:
        {:enum,
         [
           nil,
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      coupon_code: :string,
      coupon_name: :string,
      created_at: {:string, "date-time"},
      credits: [{Lago.CreditObject, :t}],
      expiration_at: {:union, [{:string, "date-time"}, :null]},
      external_customer_id: :string,
      frequency: {:enum, ["once", "recurring", "forever"]},
      frequency_duration: {:union, [:integer, :null]},
      frequency_duration_remaining: {:union, [:integer, :null]},
      lago_coupon_id: {:string, "uuid"},
      lago_customer_id: {:string, "uuid"},
      lago_id: {:string, "uuid"},
      percentage_rate: {:union, [:string, :null]},
      status: {:enum, ["active", "terminated"]},
      terminated_at: {:union, [{:string, "date-time"}, :null]}
    ]
  end
end
