defmodule Lago.InvoiceObject do
  @moduledoc """
  Provides struct and type for a InvoiceObject
  """

  @type t :: %__MODULE__{
          applied_taxes: [Lago.InvoiceAppliedTaxObject.t()] | nil,
          applied_usage_thresholds: [Lago.AppliedUsageThresholdObject.t()] | nil,
          billing_entity_code: String.t() | nil,
          billing_periods: [Lago.BillingPeriodObject.t()] | nil,
          coupons_amount_cents: integer | nil,
          created_at: DateTime.t() | nil,
          credit_notes_amount_cents: integer | nil,
          currency: String.t() | nil,
          customer: Lago.CustomerObject.t() | nil,
          fees_amount_cents: integer | nil,
          file_url: String.t() | nil,
          invoice_type: String.t() | nil,
          issuing_date: Date.t() | nil,
          lago_id: String.t() | nil,
          metadata: [Lago.InvoiceMetadataObject.t()] | nil,
          net_payment_term: integer | nil,
          number: String.t() | nil,
          payment_dispute_lost_at: DateTime.t() | nil,
          payment_due_date: Date.t() | nil,
          payment_overdue: boolean | nil,
          payment_status: String.t() | nil,
          prepaid_credit_amount_cents: integer | nil,
          progressive_billing_credit_amount_cents: integer | nil,
          self_billed: boolean | nil,
          sequential_id: integer | nil,
          status: String.t() | nil,
          sub_total_excluding_taxes_amount_cents: integer | nil,
          sub_total_including_taxes_amount_cents: integer | nil,
          taxes_amount_cents: integer | nil,
          total_amount_cents: integer | nil,
          updated_at: DateTime.t() | nil,
          version_number: integer | nil
        }

  defstruct [
    :applied_taxes,
    :applied_usage_thresholds,
    :billing_entity_code,
    :billing_periods,
    :coupons_amount_cents,
    :created_at,
    :credit_notes_amount_cents,
    :currency,
    :customer,
    :fees_amount_cents,
    :file_url,
    :invoice_type,
    :issuing_date,
    :lago_id,
    :metadata,
    :net_payment_term,
    :number,
    :payment_dispute_lost_at,
    :payment_due_date,
    :payment_overdue,
    :payment_status,
    :prepaid_credit_amount_cents,
    :progressive_billing_credit_amount_cents,
    :self_billed,
    :sequential_id,
    :status,
    :sub_total_excluding_taxes_amount_cents,
    :sub_total_including_taxes_amount_cents,
    :taxes_amount_cents,
    :total_amount_cents,
    :updated_at,
    :version_number
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      applied_taxes: [{Lago.InvoiceAppliedTaxObject, :t}],
      applied_usage_thresholds: [{Lago.AppliedUsageThresholdObject, :t}],
      billing_entity_code: {:union, [:string, :null]},
      billing_periods: [{Lago.BillingPeriodObject, :t}],
      coupons_amount_cents: :integer,
      created_at: {:string, "date-time"},
      credit_notes_amount_cents: :integer,
      currency:
        {:enum,
         [
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GHS",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      customer: {Lago.CustomerObject, :t},
      fees_amount_cents: :integer,
      file_url: {:string, "uri"},
      invoice_type:
        {:enum, ["subscription", "add_on", "credit", "one_off", "progressive_billing"]},
      issuing_date: {:string, "date"},
      lago_id: {:string, "uuid"},
      metadata: [{Lago.InvoiceMetadataObject, :t}],
      net_payment_term: :integer,
      number: :string,
      payment_dispute_lost_at: {:string, "date-time"},
      payment_due_date: {:string, "date"},
      payment_overdue: :boolean,
      payment_status: {:enum, ["pending", "succeeded", "failed"]},
      prepaid_credit_amount_cents: :integer,
      progressive_billing_credit_amount_cents: :integer,
      self_billed: :boolean,
      sequential_id: :integer,
      status: {:enum, ["draft", "finalized", "voided", "failed", "pending"]},
      sub_total_excluding_taxes_amount_cents: :integer,
      sub_total_including_taxes_amount_cents: :integer,
      taxes_amount_cents: :integer,
      total_amount_cents: :integer,
      updated_at: {:string, "date-time"},
      version_number: :integer
    ]
  end
end
