defmodule Lago.PaymentObject do
  @moduledoc """
  Provides struct and type for a PaymentObject
  """

  @type t :: %__MODULE__{
          amount_cents: integer,
          amount_currency: String.t(),
          created_at: DateTime.t(),
          external_customer_id: String.t(),
          external_payment_id: String.t() | nil,
          invoice_ids: [String.t()],
          lago_customer_id: String.t(),
          lago_id: String.t(),
          lago_payable_id: String.t(),
          next_action: map,
          payable_type: String.t(),
          payment_provider_code: String.t(),
          payment_provider_type: String.t(),
          payment_status: String.t(),
          provider_customer_id: String.t(),
          provider_payment_id: String.t() | nil,
          reference: String.t(),
          status: String.t(),
          type: String.t()
        }

  defstruct [
    :amount_cents,
    :amount_currency,
    :created_at,
    :external_customer_id,
    :external_payment_id,
    :invoice_ids,
    :lago_customer_id,
    :lago_id,
    :lago_payable_id,
    :next_action,
    :payable_type,
    :payment_provider_code,
    :payment_provider_type,
    :payment_status,
    :provider_customer_id,
    :provider_payment_id,
    :reference,
    :status,
    :type
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amount_cents: :integer,
      amount_currency:
        {:enum,
         [
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GHS",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      created_at: {:string, "date-time"},
      external_customer_id: :string,
      external_payment_id: {:union, [:string, :null]},
      invoice_ids: [string: "uuid"],
      lago_customer_id: {:string, "uuid"},
      lago_id: {:string, "uuid"},
      lago_payable_id: {:string, "uuid"},
      next_action: :map,
      payable_type: {:enum, ["Invoice", "PaymentRequest"]},
      payment_provider_code: :string,
      payment_provider_type:
        {:enum, ["adyen", "cashfree", "gocardless", "stripe", "flutterwave", "moneyhash"]},
      payment_status: {:enum, ["succeeded", "failed", "pending", "processing"]},
      provider_customer_id: :string,
      provider_payment_id: {:union, [:string, :null]},
      reference: :string,
      status: :string,
      type: {:enum, ["manual", "provider"]}
    ]
  end
end
