defmodule Lago.PlanUpdateInputPlan do
  @moduledoc """
  Provides struct and type for a PlanUpdateInputPlan
  """

  @type t :: %__MODULE__{
          amount_cents: integer | nil,
          amount_currency: String.t() | nil,
          bill_charges_monthly: boolean | nil,
          bill_fixed_charges_monthly: boolean | nil,
          cascade_updates: boolean | nil,
          charges: [Lago.PlanUpdateInputPlanCharges.t()] | nil,
          code: String.t() | nil,
          description: String.t() | nil,
          fixed_charges: [Lago.PlanUpdateInputPlanFixedCharges.t()] | nil,
          interval: String.t() | nil,
          invoice_display_name: String.t() | nil,
          metadata: map | nil,
          minimum_commitment: Lago.MinimumCommitmentInput.t() | nil,
          name: String.t() | nil,
          pay_in_advance: boolean | nil,
          tax_codes: [String.t()] | nil,
          trial_period: number | nil,
          usage_thresholds: [Lago.UsageThresholdInput.t()] | nil
        }

  defstruct [
    :amount_cents,
    :amount_currency,
    :bill_charges_monthly,
    :bill_fixed_charges_monthly,
    :cascade_updates,
    :charges,
    :code,
    :description,
    :fixed_charges,
    :interval,
    :invoice_display_name,
    :metadata,
    :minimum_commitment,
    :name,
    :pay_in_advance,
    :tax_codes,
    :trial_period,
    :usage_thresholds
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amount_cents: :integer,
      amount_currency:
        {:enum,
         [
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GHS",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      bill_charges_monthly: {:union, [:boolean, :null]},
      bill_fixed_charges_monthly: {:union, [:boolean, :null]},
      cascade_updates: :boolean,
      charges: [{Lago.PlanUpdateInputPlanCharges, :t}],
      code: :string,
      description: {:union, [:string, :null]},
      fixed_charges: [{Lago.PlanUpdateInputPlanFixedCharges, :t}],
      interval: {:enum, ["weekly", "monthly", "quarterly", "semiannual", "yearly"]},
      invoice_display_name: {:union, [:string, :null]},
      metadata: :map,
      minimum_commitment: {:union, [{Lago.MinimumCommitmentInput, :t}, :null]},
      name: :string,
      pay_in_advance: :boolean,
      tax_codes: [:string],
      trial_period: {:union, [:number, :null]},
      usage_thresholds: [{Lago.UsageThresholdInput, :t}]
    ]
  end
end
