defmodule Lago.PlanOverridesObject do
  @moduledoc """
  Provides struct and type for a PlanOverridesObject
  """

  @type t :: %__MODULE__{
          amount_cents: integer | nil,
          amount_currency: String.t() | nil,
          charges: [Lago.PlanOverridesObjectCharges.t()] | nil,
          description: String.t() | nil,
          fixed_charges: [Lago.PlanOverridesObjectFixedCharges.t()] | nil,
          invoice_display_name: String.t() | nil,
          metadata: map | nil,
          minimum_commitment: Lago.MinimumCommitmentInput.t() | nil,
          name: String.t() | nil,
          tax_codes: [String.t()] | nil,
          trial_period: number | nil,
          usage_thresholds: [Lago.UsageThresholdInput.t()] | nil
        }

  defstruct [
    :amount_cents,
    :amount_currency,
    :charges,
    :description,
    :fixed_charges,
    :invoice_display_name,
    :metadata,
    :minimum_commitment,
    :name,
    :tax_codes,
    :trial_period,
    :usage_thresholds
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amount_cents: :integer,
      amount_currency:
        {:enum,
         [
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GHS",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      charges: [{Lago.PlanOverridesObjectCharges, :t}],
      description: :string,
      fixed_charges: [{Lago.PlanOverridesObjectFixedCharges, :t}],
      invoice_display_name: :string,
      metadata: :map,
      minimum_commitment: {:union, [{Lago.MinimumCommitmentInput, :t}, :null]},
      name: :string,
      tax_codes: [:string],
      trial_period: :number,
      usage_thresholds: [{Lago.UsageThresholdInput, :t}]
    ]
  end
end
