defmodule Lago.PlanObject do
  @moduledoc """
  Provides struct and type for a PlanObject
  """

  @type t :: %__MODULE__{
          amount_cents: integer,
          amount_currency: String.t(),
          bill_charges_monthly: boolean | nil,
          bill_fixed_charges_monthly: boolean | nil,
          charges: [Lago.ChargeObject.t()] | nil,
          code: String.t(),
          created_at: DateTime.t(),
          description: String.t() | nil,
          entitlements: [Lago.PlanEntitlement.t()] | nil,
          fixed_charges: [Lago.FixedChargeObject.t()] | nil,
          interval: String.t(),
          invoice_display_name: String.t() | nil,
          lago_id: String.t(),
          metadata: map | nil,
          minimum_commitment: Lago.MinimumCommitmentObject.t() | nil,
          name: String.t(),
          pay_in_advance: boolean | nil,
          taxes: [Lago.TaxObject.t()] | nil,
          trial_period: number | nil,
          usage_thresholds: [Lago.UsageThresholdObject.t()] | nil
        }

  defstruct [
    :amount_cents,
    :amount_currency,
    :bill_charges_monthly,
    :bill_fixed_charges_monthly,
    :charges,
    :code,
    :created_at,
    :description,
    :entitlements,
    :fixed_charges,
    :interval,
    :invoice_display_name,
    :lago_id,
    :metadata,
    :minimum_commitment,
    :name,
    :pay_in_advance,
    :taxes,
    :trial_period,
    :usage_thresholds
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amount_cents: :integer,
      amount_currency:
        {:enum,
         [
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GHS",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      bill_charges_monthly: {:union, [:boolean, :null]},
      bill_fixed_charges_monthly: {:union, [:boolean, :null]},
      charges: [{Lago.ChargeObject, :t}],
      code: :string,
      created_at: {:string, "date-time"},
      description: :string,
      entitlements: [{Lago.PlanEntitlement, :t}],
      fixed_charges: [{Lago.FixedChargeObject, :t}],
      interval: {:enum, ["weekly", "monthly", "quarterly", "semiannual", "yearly"]},
      invoice_display_name: :string,
      lago_id: {:string, "uuid"},
      metadata: {:union, [:map, :null]},
      minimum_commitment: {:union, [{Lago.MinimumCommitmentObject, :t}, :null]},
      name: :string,
      pay_in_advance: :boolean,
      taxes: [{Lago.TaxObject, :t}],
      trial_period: :number,
      usage_thresholds: [{Lago.UsageThresholdObject, :t}]
    ]
  end
end
