defmodule Lago.SubscriptionObjectExtended do
  @moduledoc """
  Provides struct and type for a SubscriptionObjectExtended
  """

  @type t :: %__MODULE__{
          billing_time: String.t() | nil,
          canceled_at: DateTime.t() | nil,
          created_at: DateTime.t() | nil,
          current_billing_period_ending_at: DateTime.t() | nil,
          current_billing_period_started_at: DateTime.t() | nil,
          downgrade_plan_date: Date.t() | nil,
          ending_at: DateTime.t() | nil,
          external_customer_id: String.t() | nil,
          external_id: String.t() | nil,
          lago_customer_id: String.t() | nil,
          lago_id: String.t() | nil,
          name: String.t() | nil,
          next_plan_code: String.t() | nil,
          on_termination_credit_note: String.t() | nil,
          on_termination_invoice: String.t() | nil,
          plan: Lago.PlanObject.t() | nil,
          plan_amount_cents: integer | nil,
          plan_amount_currency: String.t() | nil,
          plan_code: String.t() | nil,
          previous_plan_code: String.t() | nil,
          started_at: DateTime.t() | nil,
          status: String.t() | nil,
          subscription_at: DateTime.t() | nil,
          terminated_at: DateTime.t() | nil,
          trial_ended_at: DateTime.t() | nil
        }

  defstruct [
    :billing_time,
    :canceled_at,
    :created_at,
    :current_billing_period_ending_at,
    :current_billing_period_started_at,
    :downgrade_plan_date,
    :ending_at,
    :external_customer_id,
    :external_id,
    :lago_customer_id,
    :lago_id,
    :name,
    :next_plan_code,
    :on_termination_credit_note,
    :on_termination_invoice,
    :plan,
    :plan_amount_cents,
    :plan_amount_currency,
    :plan_code,
    :previous_plan_code,
    :started_at,
    :status,
    :subscription_at,
    :terminated_at,
    :trial_ended_at
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      billing_time: {:enum, ["calendar", "anniversary"]},
      canceled_at: {:union, [{:string, "date-time"}, :null]},
      created_at: {:string, "date-time"},
      current_billing_period_ending_at: {:union, [{:string, "date-time"}, :null]},
      current_billing_period_started_at: {:union, [{:string, "date-time"}, :null]},
      downgrade_plan_date: {:union, [{:string, "date"}, :null]},
      ending_at: {:union, [{:string, "date-time"}, :null]},
      external_customer_id: :string,
      external_id: :string,
      lago_customer_id: {:string, "uuid"},
      lago_id: {:string, "uuid"},
      name: {:union, [:string, :null]},
      next_plan_code: {:union, [:string, :null]},
      on_termination_credit_note: {:enum, ["credit", "refund", "offset", "skip"]},
      on_termination_invoice: {:enum, ["generate", "skip"]},
      plan: {Lago.PlanObject, :t},
      plan_amount_cents: :integer,
      plan_amount_currency:
        {:enum,
         [
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GHS",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      plan_code: :string,
      previous_plan_code: {:union, [:string, :null]},
      started_at: {:union, [{:string, "date-time"}, :null]},
      status: {:enum, ["active", "canceled", "pending", "terminated"]},
      subscription_at: {:string, "date-time"},
      terminated_at: {:union, [{:string, "date-time"}, :null]},
      trial_ended_at: {:union, [{:string, "date-time"}, :null]}
    ]
  end
end
