defmodule Lago.WalletCreateInputWallet do
  @moduledoc """
  Provides struct and type for a WalletCreateInputWallet
  """

  @type t :: %__MODULE__{
          applies_to: Lago.WalletCreateInputWalletAppliesTo.t() | nil,
          code: String.t() | nil,
          currency: String.t(),
          expiration_at: DateTime.t() | nil,
          external_customer_id: String.t(),
          granted_credits: String.t() | nil,
          ignore_paid_top_up_limits_on_creation: boolean | nil,
          invoice_requires_successful_payment: boolean | nil,
          metadata: map | nil,
          name: String.t() | nil,
          paid_credits: String.t() | nil,
          paid_top_up_max_amount_cents: integer | nil,
          paid_top_up_min_amount_cents: integer | nil,
          priority: integer | nil,
          rate_amount: String.t(),
          recurring_transaction_rules: [map] | nil,
          transaction_metadata: [map] | nil,
          transaction_name: String.t() | nil
        }

  defstruct [
    :applies_to,
    :code,
    :currency,
    :expiration_at,
    :external_customer_id,
    :granted_credits,
    :ignore_paid_top_up_limits_on_creation,
    :invoice_requires_successful_payment,
    :metadata,
    :name,
    :paid_credits,
    :paid_top_up_max_amount_cents,
    :paid_top_up_min_amount_cents,
    :priority,
    :rate_amount,
    :recurring_transaction_rules,
    :transaction_metadata,
    :transaction_name
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      applies_to: {:union, [{Lago.WalletCreateInputWalletAppliesTo, :t}, :null]},
      code: {:union, [:string, :null]},
      currency:
        {:enum,
         [
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GHS",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      expiration_at: {:union, [{:string, "date-time"}, :null]},
      external_customer_id: :string,
      granted_credits: {:union, [:string, :null]},
      ignore_paid_top_up_limits_on_creation: {:union, [:boolean, :null]},
      invoice_requires_successful_payment: :boolean,
      metadata: :map,
      name: {:union, [:string, :null]},
      paid_credits: {:union, [:string, :null]},
      paid_top_up_max_amount_cents: {:union, [:integer, :null]},
      paid_top_up_min_amount_cents: {:union, [:integer, :null]},
      priority: :integer,
      rate_amount: :string,
      recurring_transaction_rules: {:union, [[:map], :null]},
      transaction_metadata: {:union, [[:map], :null]},
      transaction_name: {:union, [:string, :null]}
    ]
  end
end
